import { requestUrl } from "obsidian";

import { BrevilabsClient } from "@/LLMProviders/brevilabsClient";
import { selfHostYoutube4llm } from "@/LLMProviders/selfHostServices";
import { logWarn } from "@/logger";
import { isSelfHostModeValid } from "@/plusUtils";
import { getWebViewerService } from "@/services/webViewerService/webViewerServiceSingleton";
import { parseFormattedTimestamp } from "@/services/youtubeTranscriptFormatter";
import type {
  IYouTubeTranscriptProvider,
  ParsedYouTubeUrl,
  ProviderTranscriptResult,
  TranscriptSegment,
  YouTubeProviderRequest,
  YouTubeVideo,
} from "@/services/youtubeContextTypes";
import { getSettings } from "@/settings/model";

/**
 * Create a normalized transcript payload from plain transcript text.
 *
 * @param videoId - Source video identifier.
 * @param transcriptText - Raw transcript text.
 * @param provider - Provider identifier.
 * @param language - Transcript language.
 * @param extractionMethod - Acquisition path used to fetch the transcript.
 * @returns Normalized transcript payload with basic segment structure.
 */
export function createTranscriptFromPlainText(
  videoId: string,
  transcriptText: string,
  provider: string,
  language: string,
  extractionMethod: "captions" | "audio"
): ProviderTranscriptResult["transcript"] {
  const segments = parseTranscriptTextSegments(transcriptText);
  const plainText = segments
    .map((segment) => segment.text)
    .join(" ")
    .trim();
  return {
    videoId,
    provider,
    language,
    extractionMethod,
    isAutoGenerated: true,
    segments,
    plainText,
    formattedMarkdown: "",
    wordCount: plainText.split(/\s+/).filter(Boolean).length,
    extractedAt: Date.now(),
  };
}

/**
 * Fetch basic YouTube metadata for a canonical URL using oEmbed and page metadata.
 *
 * @param parsedUrl - Canonical YouTube URL identity.
 * @returns Best-effort YouTube metadata.
 */
export async function fetchYouTubeMetadata(parsedUrl: ParsedYouTubeUrl): Promise<YouTubeVideo> {
  const defaults: YouTubeVideo = {
    videoId: parsedUrl.videoId,
    url: parsedUrl.canonicalUrl,
    title: `YouTube video ${parsedUrl.videoId}`,
    availableLanguages: [],
    chapters: [],
  };

  try {
    const oembedUrl = `https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(parsedUrl.canonicalUrl)}`;
    const response = await requestUrl({ url: oembedUrl, method: "GET" });
    const oembed = response.json as {
      title?: string;
      author_name?: string;
      thumbnail_url?: string;
    };
    defaults.title = oembed.title?.trim() || defaults.title;
    defaults.channelName = oembed.author_name?.trim() || defaults.channelName;
    defaults.thumbnailUrl = oembed.thumbnail_url || defaults.thumbnailUrl;
  } catch (error) {
    logWarn(
      `[YouTubeTranscriptProvider] Failed to fetch oEmbed metadata for ${parsedUrl.videoId}:`,
      error
    );
  }

  try {
    const watchResponse = await requestUrl({
      url: parsedUrl.canonicalUrl,
      method: "GET",
      headers: { Accept: "text/html" },
    });
    const html = watchResponse.text;
    const metadata = extractWatchPageMetadata(html);
    defaults.title = metadata.title || defaults.title;
    defaults.channelName = metadata.channelName || defaults.channelName;
    defaults.description = metadata.description || defaults.description;
    defaults.publicationDate = metadata.publicationDate || defaults.publicationDate;
    defaults.durationSeconds = metadata.durationSeconds || defaults.durationSeconds;
  } catch (error) {
    logWarn(
      `[YouTubeTranscriptProvider] Failed to fetch watch page metadata for ${parsedUrl.videoId}:`,
      error
    );
  }

  return defaults;
}

/**
 * Shared provider coordinator for YouTube transcripts.
 */
export class YouTubeTranscriptProvider {
  private readonly providers: IYouTubeTranscriptProvider[];

  constructor(providers?: IYouTubeTranscriptProvider[]) {
    this.providers = providers ?? [
      new WebViewerYouTubeTranscriptProvider(),
      new SupadataYouTubeTranscriptProvider(),
      new BrevilabsYouTubeTranscriptProvider(),
    ];
  }

  /**
   * Fetch a transcript from the first configured provider that can serve the request.
   *
   * @param request - Provider request.
   * @returns Normalized transcript result.
   */
  async fetchTranscript(request: YouTubeProviderRequest): Promise<ProviderTranscriptResult> {
    let lastError: Error | undefined;

    for (const provider of this.providers) {
      if (!(await provider.canHandle(request))) {
        continue;
      }

      try {
        const result = await provider.fetchTranscript(request);
        if (result.transcript.segments.length > 0 || result.transcript.plainText.trim()) {
          return result;
        }
        lastError = new Error(`Provider ${provider.id} returned an empty transcript`);
      } catch (error) {
        lastError = error instanceof Error ? error : new Error(String(error));
      }
    }

    throw lastError ?? new Error("No YouTube transcript provider could handle this request");
  }
}

class WebViewerYouTubeTranscriptProvider implements IYouTubeTranscriptProvider {
  readonly id = "webviewer";

  /**
   * Check whether a matching Web Viewer tab is open for this video.
   *
   * @param request - Provider request.
   * @returns True when a matching leaf is already available.
   */
  async canHandle(request: YouTubeProviderRequest): Promise<boolean> {
    return Boolean(getWebViewerService(app).findLeafByUrl(request.parsedUrl.canonicalUrl));
  }

  /**
   * Extract transcript and metadata from an open Web Viewer YouTube tab.
   *
   * @param request - Provider request.
   * @returns Normalized Web Viewer transcript result.
   */
  async fetchTranscript(request: YouTubeProviderRequest): Promise<ProviderTranscriptResult> {
    const service = getWebViewerService(app);
    const leaf = service.findLeafByUrl(request.parsedUrl.canonicalUrl);
    if (!leaf) {
      throw new Error("Matching Web Viewer tab not found");
    }

    const result = await service.getYouTubeTranscript(leaf, {
      timeoutMs: getSettings().urlExtractionTimeoutMs,
    });
    const segments: TranscriptSegment[] = result.transcript.map((segment, index) => ({
      text: segment.text.trim(),
      startTimeSeconds: parseFormattedTimestamp(segment.timestamp) ?? index,
      endTimeSeconds: undefined,
    }));
    const plainText = segments
      .map((segment) => segment.text)
      .join(" ")
      .trim();

    return {
      video: {
        videoId: result.videoId,
        url: request.parsedUrl.canonicalUrl,
        title: result.title,
        channelName: result.channel || undefined,
        description: result.description,
        publicationDate: result.uploadDate,
        durationSeconds: parseFormattedTimestamp(result.duration || ""),
        availableLanguages: request.preferredLanguage ? [request.preferredLanguage] : [],
        chapters: [],
      },
      transcript: {
        videoId: result.videoId,
        provider: this.id,
        language: request.preferredLanguage || "unknown",
        extractionMethod: "webviewer",
        isAutoGenerated: false,
        segments,
        plainText,
        formattedMarkdown: "",
        wordCount: plainText.split(/\s+/).filter(Boolean).length,
        extractedAt: Date.now(),
      },
    };
  }
}

class SupadataYouTubeTranscriptProvider implements IYouTubeTranscriptProvider {
  readonly id = "supadata";

  /**
   * Check whether self-host transcript extraction is configured.
   *
   * @param _request - Provider request.
   * @returns True when Supadata is available.
   */
  async canHandle(_request: YouTubeProviderRequest): Promise<boolean> {
    return Boolean(isSelfHostModeValid() && getSettings().supadataApiKey);
  }

  /**
   * Fetch a YouTube transcript via the configured Supadata backend.
   *
   * @param request - Provider request.
   * @returns Normalized transcript result.
   */
  async fetchTranscript(request: YouTubeProviderRequest): Promise<ProviderTranscriptResult> {
    const response = await selfHostYoutube4llm(request.parsedUrl.canonicalUrl);
    const video = await fetchYouTubeMetadata(request.parsedUrl);
    const transcript = createTranscriptFromPlainText(
      request.parsedUrl.videoId,
      response.response.transcript,
      this.id,
      request.preferredLanguage || "unknown",
      "captions"
    );
    return { video, transcript };
  }
}

class BrevilabsYouTubeTranscriptProvider implements IYouTubeTranscriptProvider {
  readonly id = "brevilabs";

  /**
   * Brevilabs remains available as the default remote provider.
   *
   * @param _request - Provider request.
   * @returns Always true.
   */
  async canHandle(_request: YouTubeProviderRequest): Promise<boolean> {
    return true;
  }

  /**
   * Fetch a YouTube transcript through Brevilabs.
   *
   * @param request - Provider request.
   * @returns Normalized transcript result.
   */
  async fetchTranscript(request: YouTubeProviderRequest): Promise<ProviderTranscriptResult> {
    const response = await BrevilabsClient.getInstance().youtube4llm(
      request.parsedUrl.canonicalUrl
    );
    const video = await fetchYouTubeMetadata(request.parsedUrl);
    const transcript = createTranscriptFromPlainText(
      request.parsedUrl.videoId,
      response.response.transcript,
      this.id,
      request.preferredLanguage || "unknown",
      "captions"
    );
    return { video, transcript };
  }
}

function parseTranscriptTextSegments(transcriptText: string): TranscriptSegment[] {
  const lines = transcriptText
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) {
    return [];
  }

  const segments = lines.map((line, index) => {
    const match = line.match(/^\[(\d{1,2}:\d{2}(?::\d{2})?)\]\s*(.+)$/);
    if (match) {
      return {
        text: match[2].trim(),
        startTimeSeconds: parseFormattedTimestamp(match[1]) ?? index,
      };
    }

    return { text: line, startTimeSeconds: index };
  });

  return segments;
}

function extractWatchPageMetadata(html: string): {
  title?: string;
  channelName?: string;
  description?: string;
  publicationDate?: string;
  durationSeconds?: number;
} {
  const metadata: {
    title?: string;
    channelName?: string;
    description?: string;
    publicationDate?: string;
    durationSeconds?: number;
  } = {};

  const scriptMatches =
    html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi) || [];
  for (const script of scriptMatches) {
    const jsonMatch = script.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/i);
    if (!jsonMatch) {
      continue;
    }

    try {
      const raw = JSON.parse(jsonMatch[1]);
      const candidates = Array.isArray(raw)
        ? raw
        : Array.isArray(raw?.["@graph"])
          ? raw["@graph"]
          : [raw];

      for (const candidate of candidates) {
        if (candidate?.["@type"] !== "VideoObject") {
          continue;
        }

        metadata.title = typeof candidate.name === "string" ? candidate.name : metadata.title;
        metadata.description =
          typeof candidate.description === "string" ? candidate.description : metadata.description;
        metadata.publicationDate =
          typeof candidate.uploadDate === "string"
            ? candidate.uploadDate
            : metadata.publicationDate;
        metadata.channelName = resolveVideoObjectAuthor(candidate.author) || metadata.channelName;
        metadata.durationSeconds =
          parseIso8601Duration(candidate.duration) ?? metadata.durationSeconds;
      }
    } catch {
      continue;
    }
  }

  return metadata;
}

function resolveVideoObjectAuthor(author: unknown): string | undefined {
  if (typeof author === "string") {
    return author;
  }

  if (Array.isArray(author) && typeof author[0]?.name === "string") {
    return author[0].name;
  }

  if (
    typeof author === "object" &&
    author !== null &&
    typeof (author as { name?: string }).name === "string"
  ) {
    return (author as { name: string }).name;
  }

  return undefined;
}

function parseIso8601Duration(duration: unknown): number | undefined {
  if (typeof duration !== "string") {
    return undefined;
  }

  const match = duration.match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);
  if (!match) {
    return undefined;
  }

  return Number(match[1] || 0) * 3600 + Number(match[2] || 0) * 60 + Number(match[3] || 0);
}
