jest.mock("@/utils", () => ({
  ensureFolderExists: jest.fn().mockResolvedValue(undefined),
  sanitizeFilePath: jest.fn((value) => value),
}));

import { YouTubeTranscriptNoteWriter } from "@/services/youtubeTranscriptNoteWriter";

describe("YouTubeTranscriptNoteWriter", () => {
  const originalApp = global.app;
  const adapter = {
    exists: jest.fn(),
    read: jest.fn(),
    write: jest.fn(),
    mkdir: jest.fn(),
  };
  const vault = {
    adapter,
    create: jest.fn(),
    getAbstractFileByPath: jest.fn(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
    global.app = { vault } as any;
    adapter.exists.mockResolvedValue(false);
    adapter.read.mockResolvedValue("");
    adapter.write.mockResolvedValue(undefined);
    adapter.mkdir.mockResolvedValue(undefined);
    vault.create.mockResolvedValue(undefined);
    vault.getAbstractFileByPath.mockReturnValue(null);
  });

  afterAll(() => {
    global.app = originalApp;
  });

  it("creates a transcript note in the configured folder", async () => {
    const saved = await YouTubeTranscriptNoteWriter.getInstance().save(
      {
        videoId: "dQw4w9WgXcQ",
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        title: "Test Video",
        channelName: "Channel",
        availableLanguages: ["en"],
        chapters: [],
      },
      {
        videoId: "dQw4w9WgXcQ",
        provider: "brevilabs",
        language: "en",
        extractionMethod: "captions",
        isAutoGenerated: true,
        segments: [],
        plainText: "Plain transcript",
        formattedMarkdown: "[00:00] Plain transcript",
        wordCount: 2,
        extractedAt: Date.now(),
      },
      {
        outputFolder: "YouTube Transcripts",
      }
    );

    expect(saved.path).toContain("YouTube Transcripts/Test Video - dQw4w9WgXcQ.md");
    expect(vault.create).toHaveBeenCalled();
  });

  it("reuses the same file when overwrite is enabled", async () => {
    adapter.exists.mockResolvedValue(true);
    adapter.read.mockResolvedValue("existing content");

    await YouTubeTranscriptNoteWriter.getInstance().save(
      {
        videoId: "dQw4w9WgXcQ",
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        title: "Test Video",
        availableLanguages: ["en"],
        chapters: [],
      },
      {
        videoId: "dQw4w9WgXcQ",
        provider: "brevilabs",
        language: "en",
        extractionMethod: "captions",
        isAutoGenerated: true,
        segments: [],
        plainText: "Plain transcript",
        formattedMarkdown: "[00:00] Plain transcript",
        wordCount: 2,
        extractedAt: Date.now(),
      },
      {
        outputFolder: "YouTube Transcripts",
        overwriteExisting: true,
      }
    );

    expect(adapter.write).toHaveBeenCalled();
  });
});
