export type YouTubeSourceKind = "watch" | "short" | "embed" | "shortlink";

export type YouTubeExtractionMethod = "captions" | "audio" | "webviewer";

export type YouTubeCacheStatus = "hit" | "miss" | "refresh";

export type AudioTranscriptionProviderId = "disabled" | "supadata" | "brevilabs";

export interface ParsedYouTubeUrl {
  originalUrl: string;
  canonicalUrl: string;
  videoId: string;
  startTimeSeconds?: number;
  sourceKind: YouTubeSourceKind;
}

export interface VideoChapter {
  title: string;
  startTimeSeconds: number;
  endTimeSeconds?: number;
}

export interface TranscriptSegment {
  text: string;
  startTimeSeconds: number;
  endTimeSeconds?: number;
  durationSeconds?: number;
  speaker?: string;
}

export interface YouTubeVideo {
  videoId: string;
  url: string;
  title: string;
  channelName?: string;
  description?: string;
  publicationDate?: string;
  durationSeconds?: number;
  thumbnailUrl?: string;
  availableLanguages: string[];
  chapters: VideoChapter[];
}

export interface VideoTranscript {
  videoId: string;
  provider: string;
  language: string;
  extractionMethod: YouTubeExtractionMethod;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  plainText: string;
  formattedMarkdown: string;
  wordCount: number;
  tokenEstimate?: number;
  extractedAt: number;
}

export interface YouTubeTranscriptCacheEntry {
  cacheKey: string;
  video: YouTubeVideo;
  transcript: VideoTranscript;
  cachedAt: number;
  expiresAt: number;
  version: number;
}

export interface TranscriptFormattingOptions {
  includeTimestamps: boolean;
  includeChapters: boolean;
}

export interface YouTubeExtractionOptions {
  preferredLanguage?: string;
  bypassCache?: boolean;
  includeTimestamps?: boolean;
  includeChapters?: boolean;
  allowAudioFallback?: boolean;
}

export interface YouTubeExtractionResult {
  parsedUrl: ParsedYouTubeUrl;
  video: YouTubeVideo;
  transcript: VideoTranscript;
  cacheStatus: YouTubeCacheStatus;
}

export interface YouTubeProviderRequest {
  parsedUrl: ParsedYouTubeUrl;
  preferredLanguage?: string;
}

export interface ProviderTranscriptResult {
  video: YouTubeVideo;
  transcript: VideoTranscript;
}

export interface AudioTranscriptionRequest {
  parsedUrl: ParsedYouTubeUrl;
  preferredLanguage?: string;
}

export interface SavedTranscriptNote {
  path: string;
  videoId: string;
  sourceUrl: string;
  savedAt: number;
  includedSummary: boolean;
}

export interface SaveTranscriptOptions {
  outputFolder: string;
  includeSummary?: string;
  overwriteExisting?: boolean;
}

export interface IYouTubeTranscriptProvider {
  readonly id: string;
  canHandle(request: YouTubeProviderRequest): Promise<boolean>;
  fetchTranscript(request: YouTubeProviderRequest): Promise<ProviderTranscriptResult>;
}

export interface IAudioTranscriptionProvider {
  readonly id: AudioTranscriptionProviderId;
  canHandle(request: AudioTranscriptionRequest): Promise<boolean>;
  transcribeVideo(request: AudioTranscriptionRequest): Promise<ProviderTranscriptResult>;
}
