import { YouTubeExtractor } from "@/services/youtubeExtractor";
import type {
  ProviderTranscriptResult,
  YouTubeTranscriptCacheEntry,
} from "@/services/youtubeContextTypes";

jest.mock("@/settings/model", () => ({
  getSettings: jest.fn(() => ({
    preferredTranscriptLanguage: "en",
    youtubeTranscriptTimestamps: true,
    audioTranscriptionProvider: "disabled",
  })),
}));

describe("YouTubeExtractor", () => {
  const cache = {
    getLookupKey: jest.fn(
      (videoId: string, language?: string) => `${videoId}:${language || "auto"}`
    ),
    get: jest.fn<Promise<YouTubeTranscriptCacheEntry | undefined>, [string]>(),
    set: jest.fn(),
  } as any;
  const transcriptProvider = {
    fetchTranscript: jest.fn<Promise<ProviderTranscriptResult>, [any]>(),
  } as any;

  beforeEach(() => {
    jest.clearAllMocks();
    cache.get.mockResolvedValue(undefined);
  });

  it("returns cached transcripts without calling the provider", async () => {
    cache.get.mockResolvedValue({
      cacheKey: "dQw4w9WgXcQ:en",
      cachedAt: Date.now(),
      expiresAt: Date.now() + 1000,
      version: 1,
      video: {
        videoId: "dQw4w9WgXcQ",
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        title: "Cached Video",
        availableLanguages: ["en"],
        chapters: [],
      },
      transcript: {
        videoId: "dQw4w9WgXcQ",
        provider: "cache",
        language: "en",
        extractionMethod: "captions",
        isAutoGenerated: true,
        segments: [{ text: "Cached text", startTimeSeconds: 0 }],
        plainText: "Cached text",
        formattedMarkdown: "[00:00] Cached text",
        wordCount: 2,
        extractedAt: Date.now(),
      },
    });

    const extractor = new YouTubeExtractor(cache, transcriptProvider);
    const result = await extractor.extractTranscript("https://www.youtube.com/watch?v=dQw4w9WgXcQ");

    expect(result.cacheStatus).toBe("hit");
    expect(result.video.title).toBe("Cached Video");
    expect(transcriptProvider.fetchTranscript).not.toHaveBeenCalled();
  });

  it("formats and caches provider results", async () => {
    transcriptProvider.fetchTranscript.mockResolvedValue({
      video: {
        videoId: "dQw4w9WgXcQ",
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        title: "Live Video",
        description: "00:00 Intro\n01:00 Main Topic",
        availableLanguages: ["en"],
        chapters: [],
      },
      transcript: {
        videoId: "dQw4w9WgXcQ",
        provider: "remote",
        language: "en",
        extractionMethod: "captions",
        isAutoGenerated: true,
        segments: [
          { text: "Intro text", startTimeSeconds: 0 },
          { text: "Main topic text", startTimeSeconds: 60 },
        ],
        plainText: "",
        formattedMarkdown: "",
        wordCount: 0,
        extractedAt: Date.now(),
      },
    });

    const extractor = new YouTubeExtractor(cache, transcriptProvider);
    const result = await extractor.extractTranscript("https://www.youtube.com/watch?v=dQw4w9WgXcQ");

    expect(result.cacheStatus).toBe("miss");
    expect(result.video.chapters).toHaveLength(2);
    expect(result.transcript.formattedMarkdown).toContain("## Intro [00:00]");
    expect(cache.set).toHaveBeenCalled();
  });
});
