import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

import {
  buildTranscriptText,
  YoutubeTranscriptModalContent,
} from "@/components/modals/YoutubeTranscriptModal";
import type { YouTubeExtractionResult } from "@/services/youtubeContextTypes";

const extractTranscript = jest.fn();
const saveTranscript = jest.fn();
const insertIntoEditor = jest.fn();
const validateYoutubeUrl = jest.fn();
const noticeMock = jest.fn();

jest.mock("@/components/ui/button", () => ({
  Button: ({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => (
    <button {...props}>{children}</button>
  ),
}));

jest.mock("@/components/ui/input", () => ({
  Input: (props: React.InputHTMLAttributes<HTMLInputElement>) => <input {...props} />,
}));

jest.mock("@/services/youtubeExtractor", () => ({
  YouTubeExtractor: {
    getInstance: () => ({
      extractTranscript,
    }),
  },
}));

jest.mock("@/services/youtubeTranscriptNoteWriter", () => ({
  YouTubeTranscriptNoteWriter: {
    getInstance: () => ({
      save: saveTranscript,
    }),
  },
}));

jest.mock("@/settings/model", () => ({
  getSettings: jest.fn(() => ({
    youtubeTranscriptOutputFolder: "YouTube Transcripts",
  })),
}));

jest.mock("@/utils", () => ({
  insertIntoEditor: (...args: unknown[]) => insertIntoEditor(...args),
  validateYoutubeUrl: (...args: unknown[]) => validateYoutubeUrl(...args),
}));

jest.mock("@/logger", () => ({
  logError: jest.fn(),
}));

jest.mock("obsidian", () => ({
  App: class {},
  Modal: class {},
  Notice: function Notice(message: string) {
    noticeMock(message);
  },
}));

const extractionResult: YouTubeExtractionResult = {
  parsedUrl: {
    originalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    videoId: "dQw4w9WgXcQ",
    sourceKind: "watch",
  },
  video: {
    videoId: "dQw4w9WgXcQ",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    title: "Test Video",
    channelName: "Test Channel",
    availableLanguages: ["en"],
    chapters: [],
  },
  transcript: {
    videoId: "dQw4w9WgXcQ",
    provider: "brevilabs",
    language: "en",
    extractionMethod: "captions",
    isAutoGenerated: true,
    segments: [],
    plainText: "Plain transcript",
    formattedMarkdown: "[00:00] Plain transcript",
    wordCount: 2,
    extractedAt: 123,
  },
  cacheStatus: "miss",
};

describe("YoutubeTranscriptModalContent", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    validateYoutubeUrl.mockReturnValue({ isValid: true, videoId: "dQw4w9WgXcQ" });
    extractTranscript.mockResolvedValue(extractionResult);
    saveTranscript.mockResolvedValue({
      path: "YouTube Transcripts/Test Video - dQw4w9WgXcQ.md",
    });
  });

  it("downloads a transcript and saves it to the configured vault folder", async () => {
    const onClose = jest.fn();

    render(<YoutubeTranscriptModalContent onClose={onClose} />);

    fireEvent.change(screen.getByPlaceholderText("https://www.youtube.com/watch?v=..."), {
      target: { value: extractionResult.video.url },
    });
    fireEvent.click(screen.getByText("Download Transcript"));

    await screen.findByText("Test Video");
    fireEvent.click(screen.getByText("Save to Vault"));

    await waitFor(() => {
      expect(saveTranscript).toHaveBeenCalledWith(
        extractionResult.video,
        extractionResult.transcript,
        {
          outputFolder: "YouTube Transcripts",
        }
      );
    });
    expect(noticeMock).toHaveBeenCalledWith(
      "Transcript saved to YouTube Transcripts/Test Video - dQw4w9WgXcQ.md"
    );
    expect(onClose).toHaveBeenCalled();
  });

  it("inserts the normalized transcript into the editor", async () => {
    const onClose = jest.fn();

    render(<YoutubeTranscriptModalContent onClose={onClose} />);

    fireEvent.change(screen.getByPlaceholderText("https://www.youtube.com/watch?v=..."), {
      target: { value: extractionResult.video.url },
    });
    fireEvent.click(screen.getByText("Download Transcript"));

    await screen.findByText("Insert at Cursor");
    fireEvent.click(screen.getByText("Insert at Cursor"));

    await waitFor(() => {
      expect(insertIntoEditor).toHaveBeenCalledWith(
        buildTranscriptText({ extraction: extractionResult }),
        false
      );
    });
    expect(onClose).toHaveBeenCalled();
  });
});
